title: Cillian Fisher # your name (or website title) here
logo: "/images/1677094933424.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="https://www.linkedin.com/in/cillianfisher/">LinkedIn</a> 
  <br>
  <a href="images/RESUME - Cillian_Fisher .docx (1)-1.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://www.GitHub.com/cillianfisher/">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
